# name: Fast API Book Management CI/CD Pipeline

# on:
#   pull_request:
#     branches: [main]

# jobs:
#   test:
#     name: test
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout Code
#         uses: actions/checkout@v4

#       - name: Set Up Python
#         uses: actions/setup-python@v4
#         with:
#           python-version: "3.10"

#       - name: Install Dependencies
#         run: |
#           python -m venv venv
#           source venv/bin/activate
#           pip install --upgrade pip
#           pip install -r requirements.txt

#       - name: Run Tests
#         run: |
#           source venv/bin/activate
#           pytest

#   deploy:
#     name: deploy
#     runs-on: ubuntu-latest
#     needs: test

#     steps:
#       - name: Checkout Code
#         uses: actions/checkout@v4

#       - name: Setup SSH
#         uses: webfactory/ssh-agent@v0.9.0
#         with:
#           ssh-private-key: ${{ secrets.FASTAPI_SSH_KEY }}

#       - name: Deploy Docker Container
#         run: |
#           ssh -o StrictHostKeyChecking=no ubuntu@ec2-3-84-25-2.compute-1.amazonaws.com << 'EOF'
#             cd /home/ubuntu/ || git clone https://github.com/saucekode/fastapi-book-project.git /home/ubuntu/
#             cd /home/ubuntu/fastapi-book-project
#             git pull origin main
#             docker compose down
#             docker compose up --build -d
#           EOF